@echo off
REM ============================================================
REM  Make https://huye.ur.ac.rw/timetable/ use the same files as
REM  http://localhost/timetable/
REM
REM  Right-click → Run as administrator
REM  Then restart Apache in XAMPP Control Panel
REM ============================================================

setlocal EnableExtensions EnableDelayedExpansion
set "ROOT=%~dp0"
set "XAMPP=C:\xampp"

if exist "D:\xampp\apache\conf\httpd.conf" set "XAMPP=D:\xampp"
if exist "E:\xampp\apache\conf\httpd.conf" set "XAMPP=E:\xampp"

set "HTDOCS=%XAMPP%\htdocs\timetable"
set "HTDOCS_UNIX=%HTDOCS:\=/%"
set "EXTRA=%XAMPP%\apache\conf\extra\timetable-alias.conf"
set "HTTPD=%XAMPP%\apache\conf\httpd.conf"

echo.
echo XAMPP:  %XAMPP%
echo App:    %HTDOCS%
echo.

if not exist "%HTTPD%" (
  echo ERROR: httpd.conf not found. Edit XAMPP path in this bat.
  pause
  exit /b 1
)

if not exist "%HTDOCS%\index.html" (
  echo WARNING: %HTDOCS%\index.html missing.
  echo Run after-pull.bat first to build and copy the frontend.
  echo.
)

> "%EXTRA%" (
  echo # Auto-generated by enable-huye-timetable.bat — do not edit by hand
  echo Alias /timetable "%HTDOCS_UNIX%"
  echo.
  echo ^<Directory "%HTDOCS_UNIX%"^>
  echo     Options FollowSymLinks
  echo     AllowOverride All
  echo     Require all granted
  echo     CGIPassAuth On
  echo ^</Directory^>
)

echo Wrote: %EXTRA%

findstr /C:"timetable-alias.conf" "%HTTPD%" >nul 2>&1
if errorlevel 1 (
  >> "%HTTPD%" echo.
  >> "%HTTPD%" echo # UR Timetable — same /timetable for localhost and huye.ur.ac.rw
  >> "%HTTPD%" echo Include conf/extra/timetable-alias.conf
  echo Added Include line to httpd.conf
) else (
  echo Include already present in httpd.conf
)

echo.
echo Next steps:
echo   1. XAMPP Control Panel → Stop Apache → Start Apache
echo   2. Keep Node backend running ^(after-pull.bat / start-backend.bat^)
echo   3. Open https://huye.ur.ac.rw/timetable/
echo.
echo Windows Firewall: allow inbound TCP 80 and 443 if needed.
echo.
pause
